### ISSUE TITLE
Some traffic gets around wondershaper (not sure if bug)

### ISSUE THREAD

**Issue by mknod** [magnific0/wondershaper#1]
I am using wondershaper as a way to test different speed internet environments. For example a dsl connection with 512 Kb down and 64 Kb up

When I am doing this, I notice that things like speedtest.net do show the traffic as being artificially slowed down, however, things like netflix are not. I was able to determine this by opening up a terminal and running bwm-ng in real time and seeing speeds much greater than I had specified.

Here is the command I used with wondershaper:

wondershaper  -a eth0 -d 512 -u 64

Here are the rules from wondershaper:

wondershaper -a eth0 -s
qdisc cbq 1: root refcnt 2 rate 10000Kbit (bounded,isolated) prio no-transmit
 Sent 8237970 bytes 73715 pkt (dropped 0, overlimits 10115 requeues 0) 
 backlog 0b 0p requeues 0 
  borrowed 0 overactions 0 avgidle 12500 undertime 0
qdisc sfq 10: parent 1:10 limit 127p quantum 1514b depth 127 divisor 1024 perturb 10sec 
 Sent 398192 bytes 6246 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
qdisc sfq 20: parent 1:20 limit 127p quantum 1514b depth 127 divisor 1024 perturb 10sec 
 Sent 1078851 bytes 4464 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
qdisc sfq 30: parent 1:30 limit 127p quantum 1514b depth 127 divisor 1024 perturb 10sec 
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
qdisc ingress ffff: parent ffff:fff1 ---------------- 
 Sent 204846048 bytes 146905 pkt (dropped 6870, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
class cbq 1: root rate 10000Kbit (bounded,isolated) prio no-transmit
 Sent 6760927 bytes 63005 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
  borrowed 0 overactions 0 avgidle 12500 undertime 0
class cbq 1:1 parent 1: rate 64000bit (bounded,isolated) prio 5
 Sent 1476977 bytes 10709 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
  borrowed 295 overactions 0 avgidle 12500 undertime 0
class cbq 1:10 parent 1:1 leaf 10: rate 64000bit prio 1
 Sent 398126 bytes 6245 pkt (dropped 0, overlimits 5009 requeues 0) 
 backlog 0b 0p requeues 0 
  borrowed 0 overactions 1499 avgidle 12500 undertime 0
class cbq 1:20 parent 1:1 leaf 20: rate 57000bit prio 2
 Sent 1078851 bytes 4464 pkt (dropped 0, overlimits 14389 requeues 0) 
 backlog 0b 0p requeues 0 
  borrowed 295 overactions 1634 avgidle -263843 undertime -1.64269e+07
class cbq 1:30 parent 1:1 leaf 30: rate 51000bit prio 2
 Sent 0 bytes 0 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
  borrowed 0 overactions 0 avgidle 12500 undertime 0

Could this be because traffic shaping is specific to port 80 and not 443?

**Comment by magnific0** [comment]
@mknod better late then never I guess, my apologies. The incoming traffic control has been updated in version 1.4. It should work better now. To answer you question, the traffic shaping should apply to the interface, so all ports.
