### ISSUE TITLE
How to Install on Debian 9

### ISSUE THREAD

**Issue by treboR-0** [magnific0/wondershaper#14]
Your download of 1.4 is a .zip file. apt-get install wondershaper installs 1.1a-8. This file does not work well on Debian 9. I want to upgrade to 1.4. I have the .zip download. Please tell me the exact steps and commands to type to install on Debian 9. I have root access.

**Comment by magnific0** [comment]
Hi, you can simply install the package by extracting the source and typing 

    sudo make install

Which is described in the readme here https://github.com/magnific0/wondershaper/blob/master/README.md
