### ISSUE TITLE
Request for more documentation

### ISSUE THREAD

**Issue by treboR-0** [magnific0/wondershaper#15]
"Hi, you can simply install the package by extracting the source and typing

sudo make install"

I did read the instructions. I did try them too. They did nothing. Could you write detailed instructions with exact commands from what file where, to what files where. Example: Download from here, to this location, type these commands, verify and so forth. We all aren't so knowledgeable of linux. Please make your program accessible to the masses, write a proper installation tutorial so that we may all enjoy your program.

**Comment by magnific0** [comment]
Hi @treboR-0 I have expanded the installation section of the README. Could you please let me know if this is clearer in your opinion and at which steps (if any) you got stuck / would like clarification.

**Comment by magnific0** [comment]
Closing this issue.
