### ISSUE TITLE
Works on some sites, not on other

### ISSUE THREAD

**Issue by knstn-project** [magnific0/wondershaper#18]
I have enabled it permanently with systemd. While the service works as it should, i have notice that there are sites which it doesn't limit bandwidth, like Youtube and others.
On other sites like imgur works fine.
I check bandwidth in real time with netdata and i'm on firefox 58, fedora 27.

**Comment by magnific0** [comment]
I don't think the domains really matter. Perhaps this is related to the packet size. Canyou confirm you're using the latest version (1.4) of wondershaper?

**Comment by knstn-project** [comment]
A) I made the pull for first time January 31, 2018. The README.md file refers 1.4 version, but the VERSION file that came along mentions 1.3. I can't find through systemctl the version.

B) I know that Youtube (Google) uses IPv6 by default. Does Wondershaper support IPv6?

C) I have an ADSL connection of 12Mbps and three PC connected, and i have set 4Mbps down/25Kbps up, for equal bandwidth share.

**Comment by magnific0** [comment]
@knstn-project thanks for the info. I see the issue now. Wondershaper currently does not support IPv6. See also #4 . While it is possible and hopefully not too much work, it is something I don't have much time for at the moment. Also considering I don't have IPv6 or actually use wondershaper myself anymore. So I can't make any promises. 

Best thing I can advice is to leave a comment in the other thread (#4 ) so we can collect the interest in one place and you'll also be kept in the loop if I start working on it.
