### ISSUE TITLE
Ubuntu Mate 16.04 BCM2709 / BCM2836 continuous "hw csum failure" exceptions

### ISSUE THREAD

**Issue by madaello** [magnific0/wondershaper#19]
[syslog.example.log](https://github.com/magnific0/wondershaper/files/1736511/syslog.example.log)
Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Network:
2: enxb827eba318dc: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:a3:18:dc brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.131/24 brd 192.168.0.255 scope global dynamic enxb827eba318dc
       valid_lft 84219sec preferred_lft 84219sec
    inet6 fe80::7975:a397:be6c:b6a/64 scope link 
       valid_lft forever preferred_lft forever

adapter used: enxb827eba318dc

Around 300 syslog lines every 5 seconds. I don't think that is normal behaviour, do you have an explanation/solution?

**Comment by magnific0** [comment]
That is indeed very aggressive. I am surprised your network stays up as it seems to continuously crash and restart. 

I don't think this problem will can be solved easily as the script just add simple tc rules, which shouldn't cause this behaviour. There is definitely a bug in the kernel / broadcom driver here. My only suggestion is to update both to the latest version and if still persistent file a bug report with the either Ubuntu Mate or [rpi linux](https://github.com/raspberrypi/linux/issues).

**Comment by magnific0** [comment]
Oh and could you please report the output of ```uname -a``` here, so we have an idea of the kernel you're one. Thanks!

**Comment by madaello** [comment]
about uname -a
Linux umate-pi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux

I ran the same script this night (basically a curl script to upload files to dropbox) without limit the bandwidth and I didn't see any kernel error in syslog. 
However no worries, I can stay without limit the bandwidth. I just advised you of this strange behaviour in case you have a simple solution, because at the end wondershaper did the correct job but with tons of kernel lines in syslog.

**Comment by magnific0** [comment]
Sorry for the late reply. I appreciate your feedback. However, I'm closing this issue as it is quite stale. If tc is (still) spamming the syslog this should really be taken up there, as the resources on this project are very limited. Thank!
