### ISSUE TITLE
No difference in when setting less than 1 Kbps download speed

### ISSUE THREAD

**Issue by tushar-semwal** [magnific0/wondershaper#21]
I am trying to set the lo speed less than 1Kpbs i.e. for e.g. 0.001Kbps.
The command works without any error but no effect. Same as when I set at 1 Kbps.

**Comment by magnific0** [comment]
From my understanding the underlying commands will only accept integer values. So this explains your observations.

```kbit``` is hardcoded in wondershaper on [lines 140,146,153,159,238](https://github.com/magnific0/wondershaper/blob/master/wondershaper#L140-L238). You can substitute these for ```bit``` and simply give your rates in bits.

Please, let us know here how this works out for you! I have always found that the exact limits are hard to get. So especially going below kbits I am not sure what will happen.

**Comment by magnific0** [comment]
@tushar-semwal Closing this issue for now as kbps is fine-grained enough for 99.9% of the users. For users like you, it is always possible to set the base unit yourself. 
At any rate, do please still let us know here how 1bit control works out in practice. I'm really curious!
