### ISSUE TITLE
Where exactly do the files go on CentOS and Debian

### ISSUE THREAD

**Issue by treboR-0** [magnific0/wondershaper#26]
Great limiter, Thanks! But ,where exactly do the files go on CentOS and Debian. You explain the main file and I have no conf.d folder and the .service file goes where?

**Comment by treboR-0** [comment]
Tried and failed too many times to count to get this to start at boot. Please help. The .service fails to start it. Crontab commands fail. Crontab Starter.sh with commands in it fails. Yet manual start works perfectly.

**Comment by corbolais** [comment]
@treboR-0  have a look at https://github.com/magnific0/wondershaper/pull/42 where I use Debian paths.

**Comment by magnific0** [comment]
I'm closing this issue. The PR referred to @corbolais has been merged. Hopefully this provide a solution.
