### ISSUE TITLE
ECN support

### ISSUE THREAD

**Issue by dtaht** [magnific0/wondershaper#3]
While I appreciate very much you updating and maintaining wondershaper, there are a few minor problems. The first one is the ecn support field. So far as I know this should be 0xfc to correctly mask out ecn.

tc filter add dev $IFACE parent 1:0 protocol ip prio 10 u32 \
      match ip tos 0x10 0xff flowid 1:10

**Comment by dimaqq** [comment]
I'd like to see an update to wondershaper too.
For example https://wiki.gentoo.org/wiki/Traffic_shaping shows how to set up ingress shaper with ECN via ifb0.
I'd use a ready-made script like that!

**Comment by magnific0** [comment]
@dimaqq although a bit late, I did exactly that today. The ingress shaping is now much more reliable. I hope this is in line with your and @dtaht 's suggestion. I'm closing the issue for now.
