### ISSUE TITLE
Add support for packet loss. (enhancement)

### ISSUE THREAD

**Issue by RussellBradley** [magnific0/wondershaper#35]
Please add support for packet loss. Similar to Apple's NLC or Meraki's Traffic and Bandwidth shaping tools, it'll be great if we were able to control the number of packets received and lost while simulating different network conditions through wondershaper's CLI.

**Comment by magnific0** [comment]
This sounds interesting, but not how most people use wondershaper. wondershaper is just a simple wrapper to tc. Wondershaper just install and removes rules. I don't see how it could work alongside a separate project that is just a packet dropper and keep the functionality separate.

**Comment by Fuseteam** [comment]
Someone has been active today :p
