### ISSUE TITLE
run fail in tegra

### ISSUE THREAD

**Issue by ewanluser** [magnific0/wondershaper#37]
ubuntu@ubuntu-desktop:~/wondershaper$ uname -a 
Linux ubuntu-desktop 4.9.140-tegra #1 SMP PREEMPT Tue Jul 16 17:04:49 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux

root@ubuntu-desktop:/home/ubuntu/wondershaper# ./wondershaper -a eth0 -u 2048 -d 2048
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
modprobe: FATAL: Module ifb not found in directory /lib/modules/4.9.140-tegra
Cannot find device "ifb0"
RTNETLINK answers: No such file or directory
Cannot find device "ifb0"
bad action parsing
parse_action: bad value (5:mirred)!
Illegal "action"
Cannot find device "ifb0"
Cannot find device "ifb0"
Cannot find device "ifb0"

**Comment by Noel549** [comment]
Hi, i use jetson tx2 and i meet the question which is same with you. Are you solve it now?

**Comment by ewanluser** [comment]
final i found it lose sch_red.ko in the kernal and Basically you just need to build the module, "sch_red.ko", and copy it to the right place. Search for documentation here
https://developer.nvidia.com/embedded/downloads

**Comment by lotten90** [comment]
Hi ewanluser,

I meet the same problem. However, I am new for build a module on ubuntu tegra. Can you give some detailed steps for fixing this problem? Thanks.

**Comment by ewanluser** [comment]
https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-322/index.html#page/Tegra%2520Linux%2520Driver%2520Package%2520Development%2520Guide%2Fkernel_custom.html%23wwpID0E0QD0HA 
maybe help
