### ISSUE TITLE
Limit upload rate failed

### ISSUE THREAD

**Issue by w1252675615** [magnific0/wondershaper#40]
System: Ubuntu 18.04.3 LTS

<img width="519" alt="upload" src="https://user-images.githubusercontent.com/20452875/71864046-ad620300-3139-11ea-9078-774eb79d4e59.png">

As show in the picture, i limit upload rate to 1Mbit/s, but I got 1.38Mbit/s actually.

**Comment by magnific0** [comment]
Limiting is not exact unfortunately. Also ipv6 (#4) is not supported.
