### ISSUE TITLE
difference between high prio class 1:10 and default class 1:20

### ISSUE THREAD

**Issue by patatetom** [magnific0/wondershaper#41]
hi,
wouldn't it be the same formula that's used in both classes ?
```
rate $[40*$USPEED/100]kbit ceil $[95*$USPEED/100]kbit \
```

**Comment by magnific0** [comment]
Sorry can be please explain your remark further

Both classes indeed use the same formula, the only difference is the X=1 or X=2 in the example code below.

```
   tc class add dev $IFACE parent 1:1 classid 1:X0 htb \
        rate $[40*$USPEED/100]kbit ceil $[95*$USPEED/100]kbit \
        prio X $COMMONOPTIONS
```

This was equalized in a021ccd2d34d52f1b37e0973bc700c8257dfd604. @saimonn should now the reason for this. But the foggy way I remember it is that the prio 1 traffic was always above the set limit anyway. 95% more matches reality to the settings. But again, I am not sure about that one. I'll leave this open for a bit for you and or @saimonn to comment on this.

**Comment by patatetom** [comment]
yes, this is the way to understand/read my question : sorry for the lack of clarity.

I read `1:10=>95%`, `1:20=>95%` and `1:30=>90%`, so I asked myself and left you a trail of that questioning.

but I just saw that the formulas were in fact different although they both use `95%` : `1:10` uses `rate "${RATE}kbit"` and `1:20` uses `rate "${USPEED}kbit"`.

**Comment by oliverkurth** [comment]
Somewhat related to this issue - it looks to me that there is a bug somewhere here:

``` 
  RATE=$((40*"$USPEED"/100))
  if [ "$RATE" -eq 0 ]; then RATE=1 ; fi
  tc class add dev "$IFACE" parent 1:1 classid 1:20 htb \
    rate "${USPEED}kbit" ceil $((95*"$USPEED"/100))kbit \
    prio 2 ${COMMONOPTIONS[@]};
```

`RATE` is set but never used. And then `RATE` is set again further down, but never used either.

I think, but I am not sure, that it should be `rate ${RATE}` in both the `1:20` and the `1:30` classes, just like in the `1:10` class.

**Comment by magnific0** [comment]
@oliverkurth you are absolutely right. I have now fixed this.

**Comment by magnific0** [comment]
Closing the issue.
