### ISSUE TITLE
Can we make a smarter script out of this?

### ISSUE THREAD

**Issue by sonuyos** [magnific0/wondershaper#49]
The script is terrific, however anyway to make it smarter?

Like it runs after certain traffic has gone through?

Like say 1TB is set per day, once 1TB is hit, the script turns on automatically?

**Comment by magnific0** [comment]
Thanks! Nice idea for an application, I like it. However, I don't think smart features that really belong in this script because the number of ways to make it smart are endless. The easiest way is to write a small script. 

Check out vnstat. It can do the data usage monitoring.
