### ISSUE TITLE
Not all apps respecting limitations?

### ISSUE THREAD

**Issue by arbyyyyh** [magnific0/wondershaper#50]
I started out using the ubuntu package but found out that’s and old version and cloned the repo and installed as a service. I use the following command to initialize
```
sudo wondershaper -a wlan -d 600 -u 600
```
When I use citrix receiver, taking a look at nload shows limitations at the speed I set, but when I open speedtest.net or fast.com on chrome , I’m getting full speed and nload confirms. The speedtest-cli however, does respect it. I’m happy to share any of the proof with anyone if someone cares to help.

Thanks!

**Comment by mozlima** [comment]
sudo wondershaper -a **wlan** (Is your interface really this?) -d 600 -u 600

**Comment by magnific0** [comment]
I am quite sure the problem is with IPv6 which is not limited well. This issue is described in #4 and also contains a few other linked duplicate issues. The current solution is to add IPv6 to wondershaper or force only IPv4 on your interface.
