### ISSUE TITLE
Only working with eth0 not on eth1

### ISSUE THREAD

**Issue by gouyeh** [magnific0/wondershaper#52]
Hello,

I am using proxmox and i add 3 network devices in my VM (eth0, eth1, eth2)
All network devices are configured with Separate Public IP, Example: 10.10.10.1, 10.10.10.2, 10.10.10.3
If i create a limit on eth0 it applies on all interfaces eth0, eth1 and eth2.
If i only add limit on eth1 it doesn't control network speed on eth1 IP.

Please help me out with this.

Thanks

**Comment by magnific0** [comment]
Hi @gouyeh sorry for the late reply. I have no experience with using it is a VM. The only documented bypassing is with IPv6 traffic. You have given very little info for me to diagnose your issue with. Please reopen if this still occurs.
