### ISSUE TITLE
Time-based persistent usage.

### ISSUE THREAD

**Issue by jtagcat** [magnific0/wondershaper#59]
I have separate data caps for daily and nightly usage, and would like to cap only on daytime. This could be done with systemd timers, provide documentation for that.

Might /assign self, can't promise.

**Comment by magnific0** [comment]
Sorry this is more systemd usage than wondershaper. Feel free to create a pull request, but be very concise. Also just a link to some good systemd docs would be great. Maybe we can add a hints section to the readme.
