### ISSUE TITLE
unable to use wondershaper script in mac

### ISSUE THREAD

**Issue by gitty-kriti** [magnific0/wondershaper#67]
Hi, 
i want to use wondershaper in my macbook. I cloned the git repo and trying to start the script,
./wondershaper  -a eth0 -d 1024 -u 512

but getting error like,
./wondershaper: line 135: tc: command not found
./wondershaper: line 141: tc: command not found
./wondershaper: line 149: tc: command not found
./wondershaper: line 158: tc: command not found
./wondershaper: line 166: tc: command not found
./wondershaper: line 171: tc: command not found
./wondershaper: line 172: tc: command not found
./wondershaper: line 173: tc: command not found
./wondershaper: line 177: tc: command not found
./wondershaper: line 188: tc: command not found
./wondershaper: line 193: tc: command not found
./wondershaper: line 227: tc: command not found
./wondershaper: line 240: modprobe: command not found
./wondershaper: line 241: ip: command not found
./wondershaper: line 244: tc: command not found
./wondershaper: line 245: tc: command not found
./wondershaper: line 249: tc: command not found
./wondershaper: line 250: tc: command not found
./wondershaper: line 253: tc: command not found

 i have cloned the wondershaper in my home. Since, i am not able to clone it in /sbin dorectory or /usr/bin.
getting permission error
fatal: could not create work tree dir 'wondershaper': Operation not permitted

Kindly help!

Thanks

**Comment by saimonn** [comment]
wondershaper is meant to be run on a linux kernel. There's no plan to port it to MacOS for now.
