### ISSUE TITLE
Doesn't work on a Arch Linux ARM

### ISSUE THREAD

**Issue by wildeyes** [magnific0/wondershaper#8]
After installing `wondershaper-git` from the AUR, running `wondershaper -a eth0 -d 10 -u 10` yields:

``` shell
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: No such file or directory
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
```

How can I debug this situation?

**Comment by bararchy** [comment]
Having the same issue on Arch-Linux on x86-64, this is not CPU related sadly

sudo wondershaper -a wlan0 -d 10 -u 10
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: No such file or directory
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: No such file or directory
RTNETLINK answers: Invalid argument
We have an error talking to the kernel

**Comment by vitaliy-kuzmich** [comment]
confirm, does not working at arch too

**Comment by magnific0** [comment]
Sorry for the very late reply. This is very strange, I wasn't able to reproduce on x86-64. I'm closing this issue as outgoing traffic was revised in 1.3 and incoming in 1.4. I'm assuming it doesn't apply. If the problems are still occurring for you please re-open with your Linux kernel version:

    uname -a

**Comment by simon387** [comment]
hello! similar error

```
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
RTNETLINK answers: Invalid argument
We have an error talking to the kernel
What is ":1"?
Usage: ... u32 [ match SELECTOR ... ] [ link HTID ] [ classid CLASSID ]
               [ action ACTION_SPEC ] [ offset OFFSET_SPEC ]
               [ ht HTID ] [ hashkey HASHKEY_SPEC ]
               [ sample SAMPLE ] [skip_hw | skip_sw]
or         u32 divisor DIVISOR

Where: SELECTOR := SAMPLE SAMPLE ...
       SAMPLE := { ip | ip6 | udp | tcp | icmp | u{32|16|8} | mark }
                 SAMPLE_ARGS [ divisor DIVISOR ]
       FILTERID := X:Y:Z

NOTE: CLASSID is parsed at hexadecimal input.
```

on ```Linux vodafone-33461074 4.13.16-300.fc27.x86_64 #1 SMP Mon Nov 27 18:19:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by magnific0** [comment]
The what is :1 shows that you have an old version of the code. Please update to the latest version.

**Comment by simon387** [comment]
ty, I got this installation from fedora 27 repo, I am gonna try somewhere else

**Comment by magnific0** [comment]
No worries, you can manually edit /usr/bin/wondershaper and remove ":1" from one of the last lines. This fixes the warnings with the newer kernels. However, in version 1.4 both incoming and outgoing shaping are rewritten and should work much better.

**Comment by aymeniq** [comment]
> No worries, you can manually edit /usr/bin/wondershaper and remove ":1" from one of the last lines. This fixes the warnings with the newer kernels. However, in version 1.4 both incoming and outgoing shaping are rewritten and should work much better.

Hi, I am using wondershaper with Mininet to shape some links in my topology. I got the same above error when I use a python script to generate the topology, and everything is OK when I use the normal mn command to generate the network topology. Note that I am using the latest version of wondershaper 1.4.1. Any suggestins?
